/* config.h - generated by CMake. */

/* Name of package */
#define PACKAGE "${PROJECT_NAME}"

/* Version number of package */
#define VERSION "${PROJECT_VERSION}"

/* Target processor clips on negative float to int conversion. */
#cmakedefine01 CPU_CLIPS_NEGATIVE

/* Target processor clips on positive float to int conversion. */
#cmakedefine01 CPU_CLIPS_POSITIVE

/* Target processor is big endian. */
#cmakedefine01 CPU_IS_BIG_ENDIAN

/* Define to 1 if you have the `alarm' function. */
#cmakedefine01 HAVE_ALARM

/* Define to 1 if you have the <alsa/asoundlib.h> header file. */
#cmakedefine01 HAVE_ALSA

/* Set to 1 if you have libfftw3. */
#cmakedefine01 HAVE_FFTW3

/* Define to 1 if you have the <immintrin.h> header file. */
#cmakedefine HAVE_IMMINTRIN_H

/* Define if you have signal SIGALRM. */
#cmakedefine01 HAVE_SIGALRM

/* Define to 1 if you have the `signal' function. */
#cmakedefine01 HAVE_SIGNAL

/* Set to 1 if you have libsndfile. */
#cmakedefine01 HAVE_SNDFILE

/* Define to 1 if you have the <stdbool.h> header file. */
#cmakedefine HAVE_STDBOOL_H

/* Define to 1 if you have the <sys/times.h> header file. */
#cmakedefine01 HAVE_SYS_TIMES_H

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H

/* Define to 1 if the compiler supports simple visibility declarations. */
#cmakedefine HAVE_VISIBILITY

/* define fast samplerate convertor */
#cmakedefine ENABLE_SINC_FAST_CONVERTER

/* define balanced samplerate convertor */
#cmakedefine ENABLE_SINC_MEDIUM_CONVERTER

/* define best samplerate convertor */
#cmakedefine ENABLE_SINC_BEST_CONVERTER

